version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: kafeshkav2-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kafeshkav2
      MYSQL_USER: kafeshka
      MYSQL_PASSWORD: test123
    ports:
      - "3386:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
