version: '3.8'

services:
  kafeshkav2-db:
    image: redcopy/kafv2-mysql:latest
    container_name: kafeshkav2-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: kafeshkav2
      MYSQL_USER: kafeshka
      MYSQL_PASSWORD: test123
    ports:
      - "3386:3306"
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    networks:
      kaf_net:
        ipv4_address: 168.0.0.15

  app:
    image: redcopy/kafeshkav2:latest
    depends_on:
      kafeshkav2-db:
        condition: service_started
    extra_hosts:
      - kafeshka_db.loc:168.0.0.15
    environment:
         ASPNETCORE_ENVIRONMENT: Production
    ports:
      - "8088:8080"
    networks:
      kaf_net:
        ipv4_address: 168.0.0.14

  kafeshkav2fe:
    image: redcopy/kafeshkav2fe:latest  # Assuming kafeshkav2fe is the image name for the front-end
    ports:
      - "8282:80"  # Expose port 80 to access the front-end
    networks:
      kaf_net:
        ipv4_address: 168.0.0.16

networks:
  kaf_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 168.0.0.0/15
          gateway: 168.0.0.1